config/routes.rb
Databox::Application.routes.draw do
   get "facility/control/main" => "facilities#main"
   post "facility/control/EditFacility" => "facilities#edit"
   post "facility/control/UpdateFacility" => "facilities#update"
   get "facility/control/EditFacilityInventoryItems" => "facilities#edit_facility_inventory_item"
   
  match "users/sign_up" => "pages#error"

  devise_for :users,
  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations', :sessions => "users/sessions"},
  :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock'}
  devise_scope :user do
    match "party/" => "users/users#index"
    match "party/adduser" => "users/users#adduser"
    post "party/adduser"
    match "party/status" => "users/users#status"
    match "party/update_user" => "users/users#update_user"
    match "party/assign_role" => "users/users#assign_role"
    match "/users/check_email" => "users/users#check_email"
  end
  root :to => 'products#index'

  put "admins/update_user"
  put "admins/assign_role"

  get "pages/error"

  resources :products do
    collection do
      post :update_image
      post :update_product
      post :update_factory
      get :overview
      get :photos
      get :copy
      get :color
      match "weight_size/:sku" => "products#weight_size", as: :weight_size
      match "pricing/:sku" => "products#pricing", as: :pricing
      get :moq_cost
      get :child
      get :find
      post  :results
    end
  end

  resources :product_promotions do
    collection do
      post :promotions_per_page
      post :delete_promotions
      get :stores
      post :stores_per_page
      post :delete_stores
      post :update_stores
      post :insert_stores

    end
  end

  resources :promotion_codes do
    collection do
      post :promotion_codes_per_page
      post :delete_promotion_codes
      get :mass_insert
      post :mass_insert
      post :add_email
      post :add_party
      post :delete_email
      post :delete_party
      post :check_party_id
    end
  end

  resources :ship_rates do
    collection do
      post :get_for_country
      post :get_rates
      post :get_for_city_autocomplete
      post :shipment_per_page
      post :delete_shipment
      post :update_shipment
      post :get_quote
      post :get_for_country_autocomplete
    end
  end

  match "all_customers" => "customers#index", as: :all_customers

  resources :factories
  
  match "/factories/factory_detail/:party_id" => "factories#factory_detail", as: :factory_detail
  match "all_factories" => "factories#all_factories", as: :all_factories

  resources :orders do
    collection do
      get :find_return
    end
  end

  resources :promotion_rules do
    collection do
      match 'manage/:id' =>  "promotion_rules#manage"
      post '/update_promotion_rule'
      post '/update_rule_condition'
      post 'delete_rule_condition'
      post 'add_rule_condition_category'
      post 'update_rule_condition_category'
      post 'add_rule_condition_product'
      post 'update_rule_condition_product'
      post :delete_rule_action_category
      post :add_rule_action_category
      post :delete_rule_action
      post :update_rule_action
      post :delete_rule_action_product
      post :add_rule_action_product
      post :insert_rule_action
      post :delete_rule_condition_category
      post :delete_rule_condition_product
      post :add_rule_condition
      post :add_promotion_rule
      post :add_promotion_category
      post :delete_promotion_category
      post :add_promotion_product
      post :delete_promotion_product
    end
  end

  resources :promotion_rule_conditions

end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController
	before_filter :authenticate_user!

	layout "factories"
	
	def index
  #  Where can I get data for Factories.
  end

  def all_factories
    #@factories = OrderHeader.all
    if params[:search_order].blank?
    	@factories = OrderHeader.paginate(:page => params[:page], :per_page => 25)
    else
    	@factories = if params[:search_order]
    		organization = Organization.where("organization_name LIKE (?)", "%#{params[:search_order]}%").map(&:party_id)
        unless organization.empty?
          order_part = OrderPart.where("customer_party_id IN (?)", organization).map(&:order_id).uniq
          OrderHeader.where("order_id IN (?)", order_part).paginate(:page => params[:page], :per_page => 25)
        else
    			OrderHeader.where("order_id = ?", params[:search_order]).paginate(:page => params[:page], :per_page => 25)
    		end
    	end
    end
  end

	def show
	end

  def edit
  end

  def new
  end

  def create
  end

  def factory_detail
  	status = OrderItemStatus.where("description IN (?)", ["ORDER_REJECTED", "ORDER_CANCELLED"]).map(&:status_id)
  	party = Party.find(params[:party_id])
  	@organization = Organization.where("party_id = ?", params[:party_id]).first
  	order = party.order_part_parties.pluck(:order_id)
  	@factory = OrderItem.where("order_id IN (?) AND status_id NOT IN (?)", order, status)
  end

end

app/helpers/factories_helper.rb
module FactoriesHelper
	def factory_name(order_head)
		order_part = OrderPart.where("order_id = ?",order_head.order_id).first
		unless order_part.nil?
			customer_party = order_part.customer_party
			organization = customer_party.organizations
			unless organization.empty?
				organization.first.organization_name
			end
		end
	end
	def factory_party_id(order_head)
		order_part = OrderPart.where("order_id = ?",order_head.order_id).first
		unless order_part.nil?
			customer_party = order_part.customer_party
			organization = customer_party.organizations
			unless organization.empty?
				organization.first.party_id
			end
		end
	end

	def order_item_status(status_id)
		status =  OrderHeaderStatus.where("status_id = ?", status_id).first
		status.description
	end
end

app/views/factories/_header.html.haml
%header#account-header
  #pre-header
  #main-header
    .inner
      #brand.push-left
        %h2
          %a{:href => "index.html"} OrderWithMe.com
      #shop-nav
        %nav
          %ul
            %li
              %a{:href => "javascript:void(null);"} Dashboard
            %li
              %a{:href => "admin-projects.html"} Priorities
            %li
              %a{:href => "admin-products.html"} Products
            %li.active
              %a{:href => "javascript:void(null);"}
                Factories
                %i.icon-caret
              %ul
                %li
                  %a{:href => "admin-factories.html"} All Factories
                %li
                  %a{:href => "admin-all-factory-orders.html"} Factory POs
            %li
              %a{:href => "javascript:void(null);"}
                Customers
                %i.icon-caret
              %ul
                %li
                  %a{:href => "admin-customers.html"} All Customers
                %li
                  %a{:href => "admin-all-customer-orders.html"} Customer SOs
            %li
              %a{:href => "javascript:void(null);"} Warehouse
      #account-nav
        %nav
          %ul
            %li
              %a{:href => "#"}
                = current_user.email
                %i.icon-caret
              %ul
                %li= link_to "Log Out", destroy_user_session_path, method: :delete

app/views/factories/all_factories.html.erb
<div class="inner">	
	<header class="page-header no-border">
		<h1>All Factories PO's</h1>
		<div class="pagination">
			<em><strong>1 - 10</strong> of <strong>10</strong> SO's</em>
			<a href="#" class="btn btn-primary btn-small"><i class="icon-arrow-left-pink"></i></a>
			<a href="#" class="btn btn-primary btn-small"><i class="icon-arrow-right-pink"></i></a>
		</div>
		<div id="products-grid-search">
			<!-- <input type="text" placeholder="Search SO's">
			<input type="button" value="Go" class="icon-search"> -->
			<%= form_tag all_factories_path, method: "GET" do %>
			<%= text_field_tag "search_order", nil, :placeholder => "Search PO's" %>
			<%= submit_tag "", class: "icon-search" %>
			<% end %>
		</div>
	</header>

	<table class="orders-table">
		<thead>
			<tr>
				<th class="cell-customer"><a href="#">Factory<i class="icon-sort"></i></a></th>
				<th class="cell-po"><a href="#">PO# <i class="icon-sort"></i></a></th>
				<th class="cell-date sort-active"><a href="#">Order Date <i class="icon-sort icon-sort-active"></i></a></th>
				<th class="cell-items"><a href="#">Total Items <i class="icon-sort"></i></a></th>
				<th class="cell-total"><a href="#">Order Total <i class="icon-sort"></i></a></th>
				<th class="cell-balance"><a href="#">Remaining Balance <i class="icon-sort"></i></a></th>
				<th class="cell-status"><a href="#">Status <i class="icon-sort"></i></a></th>
			</tr>
		</thead>
		<tbody>
			<% @factories.each do |factory| %>
			<tr>
				<td class="cell-customer"><span> <%= link_to "#{factory_name(factory)}", factory_detail_path(factory_party_id(factory)) %> </span></td>
				<td class="cell-po"><span><a href="#"><%= factory.order_id %></a></span></td>
				<td class="cell-date"><span><%= factory.entry_date.to_date %></span></td>
				<td class="cell-items"><span>TODO</span></td>
				<td class="cell-total"><span><%= factory.grand_total.round(2) %></span></td>
				<td class="cell-balance"><span><%= factory.remaining_sub_total.round(2) %></span></td>
				<td class="cell-status"><span><%= order_item_status(factory.status_id) rescue nil %></span></td>
			</tr>
			<% end %>							
		</tbody>
	</table>

	<footer class="page-footer">
      <div id="paging">
        <%= will_paginate @factories, :previous_label => h("<"), :next_label => h(">") %>
      </div>
	</footer>

</div>

app/views/factories/index.html.erb
<div class="inner">	
	<header class="page-header no-border">
		<h1>All Customer PO's</h1>
		<div class="pagination">
			<em><strong>1 - 10</strong> of <strong>10</strong> SO's</em>
			<a href="#" class="btn btn-primary btn-small"><i class="icon-arrow-left-pink"></i></a>
			<a href="#" class="btn btn-primary btn-small"><i class="icon-arrow-right-pink"></i></a>
		</div>
		<div id="products-grid-search">
			<!-- <input type="text" placeholder="Search SO's">
			<input type="button" value="Go" class="icon-search"> -->
			<%= form_tag all_factories_path, method: "GET" do %>
			<%= text_field_tag "search_order", nil, :placeholder => "Search PO's" %>
			<%= submit_tag "", class: "icon-search" %>
			<% end %>
		</div>
	</header>

	<table class="orders-table">
		<thead>
			<tr>
				<th class="cell-customer"><a href="#">Factory<i class="icon-sort"></i></a></th>
				<th class="cell-po"><a href="#">PO# <i class="icon-sort"></i></a></th>
				<th class="cell-date sort-active"><a href="#">Order Date <i class="icon-sort icon-sort-active"></i></a></th>
				<th class="cell-items"><a href="#">Total Items <i class="icon-sort"></i></a></th>
				<th class="cell-total"><a href="#">Order Total <i class="icon-sort"></i></a></th>
				<th class="cell-balance"><a href="#">Remaining Balance <i class="icon-sort"></i></a></th>
				<th class="cell-status"><a href="#">Status <i class="icon-sort"></i></a></th>
			</tr>
		</thead>
		<tbody>
			<% @factories.each do |factory| %>
			<tr>
				<td class="cell-customer"><span> <%= link_to "#{factory_name(factory)}", factory_detail_path(factory_party_id(factory)) %> </span></td>
				<td class="cell-po"><span><a href="#"><%= factory.order_id %></a></span></td>
				<td class="cell-date"><span><%= factory.entry_date.to_date %></span></td>
				<td class="cell-items"><span>TODO</span></td>
				<td class="cell-total"><span><%= factory.grand_total.round(2) %></span></td>
				<td class="cell-balance"><span><%= factory.remaining_sub_total.round(2) %></span></td>
				<td class="cell-status"><span><%= order_item_status(factory.status_id) rescue nil %></span></td>
			</tr>
			<% end %>							
		</tbody>
	</table>

	<footer class="page-footer">
		<div class="pagination">
			<em><strong>1 - 10</strong> of <strong>10</strong> PO's</em>
			<a href="#" class="btn btn-primary btn-small"><i class="icon-arrow-left-pink"></i></a>
			<a href="#" class="btn btn-primary btn-small"><i class="icon-arrow-right-pink"></i></a>
		</div>
	</footer>

</div>

app/views/factories/index.html.haml
#main{:role => "main"}
  #brand-logo
  .inner
    %header.page-header.no-border
      %h1 All Factories
      #products-grid-search
        %a.btn.btn-small{:href => "#"} Add Factory
    %header#products-header.page-header
      #product-header-filter-container
        %h5
          %span.item-total.txt-alert 200
          Factories
        %ul.filter
          %li
            %a{:href => "#"}
              Bike Co-Op
              %i.icon-caret
            %i.icon-filter-arrow
            %ul.categories
              %li
                %a{"data-category" => ".all", :href => "#"} All
              %li
                %a{"data-category" => ".sierra", :href => "#"} Sierra Pacific Crafts
              %li
                %a{"data-category" => ".nemeon", :href => "#"} Nemeon
              %li
                %a{"data-category" => ".accessories", :href => "#"} Fashion Accessories
        .pagination
          %em
            %strong 1 - 15
            of
            %strong 100
            Factories
          %a.btn.btn-primary.btn-small{:href => "#"}
            %i.icon-arrow-left-pink
          %a.btn.btn-primary.btn-small{:href => "#"}
            %i.icon-arrow-right-pink
      #products-grid-search
        %input{:placeholder => "Search Factories", :type => "text"}
          %input.icon-search{:type => "button", :value => "Go"}
    %table.orders-table
      %thead
        %tr
          %th.cell-customer
            %a{:href => "#"}
              ID
              %i.icon-sort
          %th.cell-customer.sort-active
            %a{:href => "#"}
              Factory
              %i.icon-sort.icon-sort-active
          %th.cell-market
            %a{:href => "#"}
              Categories
              %i.icon-sort
          %th.cell-store
            %a{:href => "#"}
              Marketplace
              %i.icon-sort
          %th.cell-address
            %a{:href => "#"}
              SKUs Ordered
              %i.icon-sort
          %th.cell-phone
            %a{:href => "#"}
              Revenue
              %i.icon-sort
          %th.cell-total
            %a{:href => "#"}
              Rating
              %i.icon-sort
      %tbody
        %tr
          %td.cell-customer
            %span
              %a{:href => "#"} #98736
          %td.cell-customer
            %span
              %a{:href => "#"} Beth Ellan
          %td.cell-market
            %span Hang Bags
          %td.cell-store
            %span Sierra Pacific Crafts
          %td.cell-address
            %span 15
          %td.cell-phone
            %span $900
          %td.cell-total
            %span A+

    %footer.page-footer
      .pagination
        %em
          %strong 1 - 15
          of
          %strong 100
          Factories
        %a.btn.btn-primary.btn-small{:href => "#"}
          %i.icon-arrow-left-pink
        %a.btn.btn-primary.btn-small{:href => "#"}
          %i.icon-arrow-right-pink
%script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"}
:javascript
  window.jQuery || document.write('<\/script>')